Improve managing the stage results
Signed-off-by: Dennis Behm <dennis.behm@de.ibm.com>

diff --git a/Templates/JenkinsPipeline/Jenkinsfile b/Templates/JenkinsPipeline/Jenkinsfile
--- a/Templates/JenkinsPipeline/Jenkinsfile
+++ b/Templates/JenkinsPipeline/Jenkinsfile
@@ -155,6 +155,7 @@ pipeline {
 
 	options {
 		checkoutToSubdirectory("${AppName}") // Added AppName for checkout dir of implizit checkout
+		disableConcurrentBuilds() 			 // throttle builds
 	}
 	environment {
 		GIT_TRACE       = 'false'               // Trace git for testing  true/false,1,2.
@@ -226,6 +227,8 @@ pipeline {
 					
 					//Build directory
 					BuildDir       = "${WORKSPACE}"
+					baselineReferenceFile = "${BuildDir}/${AppName}/application-conf/baselineReference.config"
+
 
 					// Branch Control Setup
 					Branch         = env.BRANCH_NAME.toUpperCase()
@@ -241,7 +244,6 @@ pipeline {
 						ucdDoDeployment = true  // Perform the Deployment.
 
 						ucdVersionName = "${ucdVersionName}-Main-${PipelineTypeUpper}" // Package Version Name Prefix.
-						baselineReferenceFile = "${BuildDir}/${AppName}/application-conf/baselineReference.config"
 
 						BranchOkay = true
 					}
@@ -436,10 +438,18 @@ pipeline {
 							println("${PipelineName}[WARN]: ${Msg}")
 							createSummary icon:"error.svg", text: "${MsgHdr} ${Msg}"
 						
-							currentBuild.result = "FAILURE" // Mark the job as failed.
-						
 							ucdDoPackaging  = false // Do not package if nothing was built.
 							ucdDoDeployment = false // Do not deploy is nothing was built.
+
+							if (Buildrc == 4) { // Mark Build unstable
+								unstable "DBB Build Warning. No source changes detected."
+							} else { // Mark Stage as Error
+								sonarQubeDoScan = false // Do not scan the repo.
+								catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
+									sh "echo 'DBB Build Error. Please check log.' && exit ${Buildrc}"
+								}
+							}
+
 						}
 				}
 			}
@@ -548,7 +558,7 @@ pipeline {
 						else
 							ucdVer="${ucdVersionName}-\${newVersionTag}-${BuildNumber}"
 						fi
-						# This log message is fetched for to specify the version name in the deployment stage
+						# This log message is fetched in a later step to define the UCD component version for the deployment stage
 						echo "${PipelineName}[INFO] Computed UCD component version name: \${ucdVer}" 
 
 						CMD="ucdPackaging.sh -w ${BuildDir} -v \${ucdVer} -c ${ucdComponent}  -u ${env.BUILD_URL} -b ${AppBranch} -e /var/jenkins/zappbuild_config/MortgageAppArtifactRepository.properties"
@@ -574,38 +584,40 @@ pipeline {
 						println("${PipelineName}[INFO]: Gathering UCD Component Version Name and URL.")
 
 						// Locate the UCD Component Version Name in the output log.
-						def ucdVersionNamePattern = java.util.regex.Pattern.compile(".*Computed UCD component version name: (.*)")
-						def ucdVersionMatcher = ucdVersionNamePattern.matcher(readFile("${ucdBuzToolLog}"))
-						if (ucdVersionMatcher.find()) {
-							ucdVersionName = "${ucdVersionMatcher.group(1)}"
-							ucdVersionMatcher = null // Prevent java.io.NotSerializableException: java.util.regex.Matcher Exception.
+						ucdVersionName = searchLogOutput(".*Computed UCD component version name: (.*)", readFile("${ucdBuzToolLog}")) // passed into subsequent stage
+						if (ucdVersionName){
 							println("${PipelineName}[INFO]: UCD Component Version Name: ${ucdVersionName}")
+							
+							// Locate the UCD Component Version URL in the output log.
+							def ucdVersionUrl = searchLogOutput("version.url -> (.*)", readFile("${ucdBuzToolLog}"))
+							if (ucdVersionUrl){
+								println("${PipelineName}[INFO]: UCD Component Version URL: ${ucdVersionUrl}")
+								createSummary icon:"accept.svg", text: "${MsgHdr} <a href=\'$ucdVersionUrl\' target=\'_other\'>UCD Component Version (name: $ucdVersionName)</a>"
+							} else {
+								Msg = "Fetching the UCD Component Version URL failed. Please check ${ucdBuzToolLogName}"
+								createSummary icon:"warning.svg", text: "${MsgHdr} ${Msg}"
+							}
 						} else {
-							Msg = "Fetching the UCD Component Version Name failed. Please check ${ucdBuzToolLogName}."
+							Msg = "Fetching the UCD Component Version Name failed. Please check ${ucdBuzToolLogName}"
 							println("${PipelineName}[WARN]: ${Msg}")
 							createSummary icon:"error.svg", text: "${MsgHdr} ${Msg}"
-							currentBuild.result = "FAILURE" // Mark the job as failed.
 							ucdDoDeployment = false // Do not deploy if packaging failed.
+							// Mark the job and stage as failed.
+							catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
+									sh "echo 'Fetching the UCD Component Version Name failed. Please check log.' && exit 1"
+							}	
 						}
-						
-						// Locate the UCD Component Version URL in the output log.
-						def buzpattern = java.util.regex.Pattern.compile("version.url -> (.*)")
-						def buzmatcher = buzpattern.matcher(readFile("${ucdBuzToolLog}"))
-						if (buzmatcher.find()) {
-							def buzrequestURL = "${buzmatcher.group(1)}"
-							buzmatcher = null // Prevent java.io.NotSerializableException: java.util.regex.Matcher Exception.
-							println("${PipelineName}[INFO]: UCD Component Version URL: ${buzrequestURL}")
-							createSummary icon:"accept.svg", text: "${MsgHdr} <a href=\'$buzrequestURL\' target=\'_other\'>UCD Component Version (name: $ucdVersionName)</a>"
-						}
+	
 						// End of if (Packagerc == 0)
 					} else {
 						Msg = "Packaging resulted in a return code=${Packagerc}. Refer to ${ucdBuzToolLogName}."
 						println("${PipelineName}[WARN]: ${Msg}")
 						createSummary icon:"error.svg", text: "${MsgHdr} ${Msg}"
-						
-						currentBuild.result = "FAILURE" // Mark the job as failed.
-						
 						ucdDoDeployment = false // Do not deploy if packaging failed.
+						// Mark the job and stage as failed.
+						catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
+									sh "echo 'Packaging script returned rc=${Packagerc}. Please check log.' && exit ${Packagerc}"
+						}
 					}
 					
 					if (pipeverbose) {
@@ -648,24 +660,28 @@ pipeline {
 							tee("${ucdDeploymentLog}") {
 								UcdDeployrc = sh(script: "${UcdDeployCmd}", returnStatus: true)
 							}
-
 							if (UcdDeployrc == 0) {
+
 								println("${PipelineName}[INFO]: Gathering UCD Deployment Request URL.")
 								
-								// Locate the UCD Deployment Request URL in the output log.
-								def ucdpattern = java.util.regex.Pattern.compile("Follow Process Request: (.*)")
-								def ucdmatcher = ucdpattern.matcher(readFile("${ucdDeploymentLog}"))
-								if (ucdmatcher.find()) {
-									def ucdrequestURL = "${ucdmatcher.group(1)}"
-									ucdmatcher = null // Prevent java.io.NotSerializableException: java.util.regex.Matcher Exception.
-									println("${PipelineName}[INFO]: UCD Deployment Request: ${ucdrequestURL}")
-									createSummary icon:"accept.svg", text: "${MsgHdr} <a href=\'$ucdrequestURL\' target=\'_other\'>UCD Deployment Request</a>"
-									}		
+								def ucdDeployRequestUrl = searchLogOutput("Follow Process Request: (.*)", readFile("${ucdDeploymentLog}"))
+								if (ucdDeployRequestUrl){
+									println("${PipelineName}[INFO]: UCD Deployment Request: ${ucdDeployRequestUrl}")
+									createSummary icon:"accept.svg", text: "${MsgHdr} <a href=\'$ucdDeployRequestUrl\' target=\'_other\'>UCD Deployment Request</a>"
+								} else {
+									Msg = "Could not retrieve UCD Deployment Request URL."
+									println("${PipelineName}[WARN]: ${Msg}")
+									createSummary icon:"warning.svg", text: "${MsgHdr} ${Msg}"
+								}
+								
 							} else {
 								Msg = "UCD Deployment request resulted in a return code=${UcdDeployrc}. Refer to ${ucdDeploymentLogName}."
 								println("${PipelineName}[WARN]: ${Msg}")
 								createSummary icon:"error.svg", text: "${MsgHdr} ${Msg}"
-								currentBuild.result = "FAILURE" // Mark the job as failed.
+								// Mark the job and stage as failed.
+								catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
+									sh "echo 'UCD Deployment request resulted in a return code=${UcdDeployrc}. Please check log.' && exit ${UcdDeployrc}"
+								}
 							}
 						}
 					}
@@ -724,3 +740,19 @@ pipeline {
 		} // End: stage ('Final Cleanup')
 	} // End: stages
 } // End: pipeline
+
+/**
+ * Methods that perform non-serializable actions
+ */
+
+@NonCPS
+def searchLogOutput(String regexPattern, String logFileContent){
+	pattern = java.util.regex.Pattern.compile(regexPattern)
+	def pMatcher = pattern.matcher(logFileContent)
+	if (pMatcher.find()) {
+		def result = "${pMatcher.group(1)}"
+		return result
+	} else {
+		return null
+	}
+}
